# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default: go run ./...
  install: go install ./...
  test:
    cmds:
      - go build -tags "fake" -o modup-test .
#      - defer: rm modup-test
      - ./modup-test
